-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 10:54:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Alphabet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alphabet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alphabet` DEFAULT CHARACTER SET utf8 ;
USE `Alphabet` ;

-- -----------------------------------------------------
-- Table `Alphabet`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Rating` (
  `idRating` INT NOT NULL,
  `Rating` INT NOT NULL,
  `Rating_Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idRating`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Group` (
  `idGroup` INT NOT NULL,
  `Group_Name` VARCHAR(45) NULL,
  `Rating_idRating` INT NOT NULL,
  PRIMARY KEY (`idGroup`, `Rating_idRating`),
  INDEX `fk_Group_Rating1_idx` (`Rating_idRating` ASC),
  CONSTRAINT `fk_Group_Rating1`
    FOREIGN KEY (`Rating_idRating`)
    REFERENCES `Alphabet`.`Rating` (`idRating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Role` (
  `idRole` INT NOT NULL,
  `Role_Name` VARCHAR(45) NULL,
  `Role_Code` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Parent_Person_ID` INT NULL,
  `Group_idGroup` INT NOT NULL,
  `Role_idRole` INT NOT NULL,
  `Rating_idRating` INT NOT NULL,
  PRIMARY KEY (`idPerson`, `Group_idGroup`, `Role_idRole`, `Rating_idRating`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  INDEX `fk_Person_Group1_idx` (`Group_idGroup` ASC),
  INDEX `fk_Person_Role1_idx` (`Role_idRole` ASC),
  INDEX `fk_Person_Rating1_idx` (`Rating_idRating` ASC),
  CONSTRAINT `fk_Person_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Alphabet`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `Alphabet`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Rating1`
    FOREIGN KEY (`Rating_idRating`)
    REFERENCES `Alphabet`.`Rating` (`idRating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Skill` (
  `idSkill` INT NOT NULL AUTO_INCREMENT,
  `Skill_Name` VARCHAR(45) NULL,
  `Skill_Description` TEXT(100) NULL,
  `Parent_Skill_ID` INT NULL,
  `Date_Created` DATETIME NULL,
  `Person_idPerson` INT NOT NULL,
  `Rating_idRating` INT NOT NULL,
  PRIMARY KEY (`idSkill`, `Person_idPerson`, `Rating_idRating`),
  INDEX `fk_Category_Person1_idx` (`Person_idPerson` ASC),
  INDEX `fk_Skill_Rating1_idx` (`Rating_idRating` ASC),
  CONSTRAINT `fk_Category_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `Alphabet`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skill_Rating1`
    FOREIGN KEY (`Rating_idRating`)
    REFERENCES `Alphabet`.`Rating` (`idRating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Practice_Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Practice_Stage` (
  `idPractice_Stage` INT NOT NULL,
  `Stage` VARCHAR(45) NULL,
  PRIMARY KEY (`idPractice_Stage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Practice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Practice` (
  `idPractice` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Skill_idSkill` INT NOT NULL,
  `Practice_Stage_idPractice_Stage` INT NOT NULL,
  PRIMARY KEY (`idPractice`, `Skill_idSkill`, `Practice_Stage_idPractice_Stage`),
  INDEX `fk_Practice_Practice_Stage1_idx` (`Practice_Stage_idPractice_Stage` ASC),
  INDEX `fk_Practice_Skill1_idx` (`Skill_idSkill` ASC),
  CONSTRAINT `fk_Practice_Skill1`
    FOREIGN KEY (`Skill_idSkill`)
    REFERENCES `Alphabet`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Practice_Practice_Stage1`
    FOREIGN KEY (`Practice_Stage_idPractice_Stage`)
    REFERENCES `Alphabet`.`Practice_Stage` (`idPractice_Stage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Progress` (
  `idProgress` INT NOT NULL AUTO_INCREMENT,
  `Progress` VARCHAR(45) NULL,
  `Role_idRole` INT NOT NULL,
  `idProgress_Parent` INT NULL,
  PRIMARY KEY (`idProgress`, `Role_idRole`),
  INDEX `fk_Skill_Progress_Role1_idx` (`Role_idRole` ASC),
  INDEX `fk_Skill_Progress_Parent1_idx` (`idProgress_Parent` ASC),
  CONSTRAINT `fk_Skill_Progress_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `Alphabet`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skill_Progress_Parent1`
    FOREIGN KEY (`idProgress_Parent`)
    REFERENCES `Alphabet`.`Progress` (`idProgress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Person_Skill_Progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Person_Skill_Progress` (
  `idPerson_Skill_Progress` INT NOT NULL,
  `Skill_idSkill` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `Progress_idProgress` INT NOT NULL,
  PRIMARY KEY (`idPerson_Skill_Progress`, `Skill_idSkill`, `Person_idPerson`, `Progress_idProgress`),
  INDEX `fk_Person_Skill_Person1_idx` (`Person_idPerson` ASC),
  INDEX `fk_Person_Skill_Skill1_idx` (`Skill_idSkill` ASC),
  INDEX `fk_Person_Skill_Skill_Progress1_idx` (`Progress_idProgress` ASC),
  CONSTRAINT `fk_Person_Skill_Skill1`
    FOREIGN KEY (`Skill_idSkill`)
    REFERENCES `Alphabet`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Skill_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `Alphabet`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Skill_Skill_Progress1`
    FOREIGN KEY (`Progress_idProgress`)
    REFERENCES `Alphabet`.`Progress` (`idProgress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alphabet`.`Skill_Prerequesite_Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alphabet`.`Skill_Prerequesite_Skill` (
  `idSkill_Prerequesite_Skill` INT NOT NULL,
  `Skill_idSkill` INT NOT NULL,
  `Skill_Prerequesiteid` INT NULL,
  PRIMARY KEY (`idSkill_Prerequesite_Skill`, `Skill_idSkill`),
  INDEX `fk_Skill_Prerequesite_Skill_Skill1_idx` (`Skill_idSkill` ASC),
  INDEX `fk_Skill_Prerequesite_Skill_Prerequesite_Skill1_idx` (`Skill_Prerequesiteid` ASC),
  CONSTRAINT `fk_Skill_Prerequesite_Skill_Skill1`
    FOREIGN KEY (`Skill_idSkill`)
    REFERENCES `Alphabet`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skill_Prerequesite_Skill_Prerequesite_Skill1`
    FOREIGN KEY (`Skill_Prerequesiteid`)
    REFERENCES `Alphabet`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
